### ISSUE TITLE
Chỉnh sửa thêm service PostgresSQL

### ISSUE THREAD

**Issue by Sang2306** [kampvie/fastapi_project_pattern#16]
Hỏi người dùng có muốn tích hợp PostgreSQL không mới cho khởi tạo

**Comment by hspaces** [comment]
Remove khối service khi người dùng chọn không sử dụng

**Comment by Sang2306** [comment]
Xóa khối service khi người dùng không chọn sử dụng khởi tạo dịch vụ PostgreSQL
